name = "StressStrainCurves"
uuid = "13c63290-a4b3-4d3c-a451-528dd2a6a092"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
